import { readDir, readTextFile, writeTextFile, remove, exists } from "@tauri-apps/plugin-fs";
import { appCacheDir, join } from "@tauri-apps/api/path";
import { invoke } from "@tauri-apps/api/core";
import { revealItemInDir } from "@tauri-apps/plugin-opener";
import type { TranscriptSegment } from "./transcript";
import type { AudioEvent } from "./asr";
import { useMockBackend } from "./env";
import { rememberMockDuration, seedMockRecordings } from "./mock/fixtures";
import { getRecordingDirectory } from "./recordingLocation";

/**
 * Persists finished recordings so the history sidebar can browse them across
 * app restarts. `src-tauri/src/capture.rs` already writes the audio WAV to
 * `<app cache dir>/recordings/<id>.wav` (`id` is a local-time timestamp stem
 * like `rec-20260813-084500`, generated by `capture.ts`'s `defaultName`).
 * Nothing else survives a restart today -- `segments`/`audioEvents` only ever
 * live in the Zustand store. This module adds a sidecar `<id>.json` next to
 * the WAV with everything the sidebar and the reopened transcript need, so
 * no new Rust command is required: `@tauri-apps/plugin-fs` (already a
 * dependency) reads/writes it directly from the frontend.
 */

export interface RecordingHistoryMeta {
  /** The filename stem shared with the WAV, e.g. "rec-20260813-084500". */
  id: string;
  /** Parsed back out of `id` rather than stored separately, since the
   * filename is already the source of truth for when the recording started
   * (see `capture.ts`'s `defaultName`) -- one fewer thing that could drift. */
  createdAt: Date;
  durationSec: number;
  language: string;
  /**
   * Whether this recording has been through the transcription pass at all.
   * `false` for takes made in record-only mode (see `finishRecordOnly` in
   * `appStore.ts`), whose sidecar exists only so the WAV is browsable and
   * re-analyzable -- its `segments` are empty and its `preview` is blank.
   * Everything else about the entry is real, so the sidebar renders it as a
   * normal row with an "unanalyzed" badge rather than hiding it.
   */
  transcribed: boolean;
  usedDiarize: boolean;
  usedVad: boolean;
  usedAudioEvents: boolean;
  /** First ~80 characters of the transcript, for the sidebar row. */
  preview: string;
}

export interface RecordingHistoryEntry extends RecordingHistoryMeta {
  segments: TranscriptSegment[];
  audioEvents: AudioEvent[];
}

/** On-disk JSON shape. Kept separate from `RecordingHistoryEntry` because
 * `createdAt` round-trips through JSON as a string, and derived fields
 * (`preview`) are computed on read rather than trusted from disk.
 *
 * Exported only so `mock/fixtures.ts` can type its seeded entries against it
 * (a type-only import, so it adds no runtime edge back to this module). */
export interface StoredRecording {
  durationSec: number;
  language: string;
  /**
   * Optional on disk, required in memory: every sidecar written before
   * record-only mode existed came from the transcription pass, so a missing
   * field means `true`. Reading it as `stored.transcribed ?? true` is what
   * keeps those older recordings from all showing up as "unanalyzed".
   */
  transcribed?: boolean;
  usedDiarize: boolean;
  usedVad: boolean;
  usedAudioEvents: boolean;
  segments: TranscriptSegment[];
  audioEvents: AudioEvent[];
}

// Mock backend only (see ./env.ts) -- an in-memory stand-in for the sidecar
// JSON files on disk, so history can be filed/browsed/deleted while
// exercising screen transitions in a plain browser. Resets on reload, same
// as every other piece of mock state in this app.
//
// Seeded rather than empty: the sidebar, playback, re-analysis and deletion
// are all reachable the moment the page opens instead of only after a real
// microphone recording -- see `seedMockRecordings`' doc comment.
const mockStore = new Map<string, StoredRecording>(useMockBackend ? seedMockRecordings() : []);

/** Follows the user's configured auto-save folder (`AutoSaveSettings.directory`
 * via `recordingLocation.ts`) when one is set, falling back to the app's own
 * cache directory otherwise -- the same choice `capture.rs`'s `recording_path`
 * makes on the Rust side, kept in sync so the frontend looks in the same
 * place the WAV actually landed. */
async function recordingsDir(): Promise<string> {
  const configured = getRecordingDirectory();
  if (configured) return configured;
  return join(await appCacheDir(), "recordings");
}

async function jsonPath(id: string): Promise<string> {
  return join(await recordingsDir(), `${id}.json`);
}

/** Exported for `appStore.ts`'s `rerunHistoryEntry`, which needs the WAV
 * path to re-run the accuracy pass without a new Rust command -- the same
 * commands `refineRecording` already calls (`transcribeRecording` etc.) just
 * take a path string, so the frontend can point them at any past
 * recording's WAV, not only the one just finished. */
export async function wavPath(id: string): Promise<string> {
  if (useMockBackend) return `mock-recordings/${id}.wav`;
  return join(await recordingsDir(), `${id}.wav`);
}

/** Opens the OS file manager on this recording's WAV, so the user can find
 * the folder it (and its sidecar JSON / auto-saved transcript, if any) live
 * in -- whichever folder that currently is, internal cache or a configured
 * auto-save directory (see `recordingsDir`). A plain browser tab has no file
 * manager to hand off to, so this is a no-op there, same as every other
 * native-only action in this module. */
export async function openRecordingFolder(id: string): Promise<void> {
  if (useMockBackend) {
    console.info("[mock] revealing a recording's folder is unavailable in the browser preview");
    return;
  }
  await revealItemInDir(await wavPath(id));
}

/** Inverse of `capture.ts`'s `defaultName`. Returns `null` for a filename
 * that doesn't match the expected stem shape, so a stray or future file
 * format in the recordings directory is skipped rather than crashing the
 * whole list. Exported for `autoSave.ts`, which needs the same wall-clock
 * start to timestamp the auto-saved transcript's lines in absolute time. */
export function parseCreatedAt(id: string): Date | null {
  const m = /^rec-(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})(\d{2})$/.exec(id);
  if (!m) return null;
  const [, y, mo, d, h, mi, s] = m;
  const date = new Date(Number(y), Number(mo) - 1, Number(d), Number(h), Number(mi), Number(s));
  return Number.isNaN(date.getTime()) ? null : date;
}

function previewFrom(segments: TranscriptSegment[]): string {
  const text = segments
    .map((s) => s.text.trim())
    .filter(Boolean)
    .join(" ");
  return text.length > 80 ? `${text.slice(0, 80)}…` : text;
}

function metaFromStored(id: string, createdAt: Date, stored: StoredRecording): RecordingHistoryMeta {
  return {
    id,
    createdAt,
    durationSec: stored.durationSec,
    language: stored.language,
    transcribed: stored.transcribed ?? true,
    usedDiarize: stored.usedDiarize,
    usedVad: stored.usedVad,
    usedAudioEvents: stored.usedAudioEvents,
    preview: previewFrom(stored.segments),
  };
}

/**
 * Writes the sidecar JSON for a just-finished recording. `id` must be the
 * same stem `capture.start()` used for the WAV -- see `wavPath`/`jsonPath`.
 * A full overwrite each time, so it's safe to call more than once for the
 * same `id` as better data becomes available.
 *
 * `recordingPipeline.ts`'s `refineRecording` calls this twice: once right
 * after the recording stops (with whatever the live pass already produced,
 * so the take is immediately visible/selectable in the sidebar), and again
 * once the second pass (and any diarization/audio-event passes) finish, to
 * overwrite the provisional entry with the refined result. A failure here is
 * reported the same way every other post-processing failure in that
 * function is: a `refineNotice`, not an error that discards the transcript
 * already on screen -- the recording not being *browsable later* is a
 * smaller loss than losing it *right now*.
 */
export async function saveRecordingHistory(
  id: string,
  entry: Omit<RecordingHistoryEntry, "id" | "createdAt" | "preview">,
): Promise<void> {
  const stored: StoredRecording = {
    durationSec: entry.durationSec,
    language: entry.language,
    transcribed: entry.transcribed,
    usedDiarize: entry.usedDiarize,
    usedVad: entry.usedVad,
    usedAudioEvents: entry.usedAudioEvents,
    segments: entry.segments,
    audioEvents: entry.audioEvents,
  };
  if (useMockBackend) {
    mockStore.set(id, stored);
    // Keeps the synthetic WAV `wavToBlobUrl` hands to playback the same
    // length as the entry the sidebar shows, including for a take whose
    // duration only became known when the (mock) capture finished.
    rememberMockDuration(id, stored.durationSec);
    return;
  }
  await writeTextFile(await jsonPath(id), JSON.stringify(stored));
}

/**
 * Lists past recordings, newest first. Reads and parses every sidecar JSON
 * (there is no separate lightweight index -- see the design plan for why
 * that's an acceptable tradeoff at the scale a single user's recordings
 * reach) but only keeps the small projected fields in the returned array, so
 * memory stays proportional to the recording count, not the transcript
 * length.
 *
 * A single corrupt or unreadable entry is skipped rather than failing the
 * whole list -- one bad file must not hide every other recording.
 */
export async function listRecordings(): Promise<RecordingHistoryMeta[]> {
  if (useMockBackend) {
    const metas: RecordingHistoryMeta[] = [];
    for (const [id, stored] of mockStore) {
      const createdAt = parseCreatedAt(id);
      if (createdAt) metas.push(metaFromStored(id, createdAt, stored));
    }
    return metas.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  const dir = await recordingsDir();
  if (!(await exists(dir))) return [];

  const entries = await readDir(dir);
  const metas: RecordingHistoryMeta[] = [];
  for (const entry of entries) {
    if (entry.isDirectory || !entry.name.endsWith(".json")) continue;
    const id = entry.name.slice(0, -".json".length);
    const createdAt = parseCreatedAt(id);
    if (!createdAt) continue;
    try {
      const raw = await readTextFile(await join(dir, entry.name));
      const stored = JSON.parse(raw) as StoredRecording;
      metas.push(metaFromStored(id, createdAt, stored));
    } catch (err) {
      console.warn(`[history] skipping unreadable recording ${id}:`, err);
    }
  }

  return metas.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}

/**
 * Shortest interrupted take worth putting in front of the user. Below this a
 * recovered entry is noise: a take that was started and lost within a second
 * has nothing in it to recover, and the WAV is more likely a stray file than
 * something someone wants back.
 */
const MIN_RECOVERABLE_SEC = 1;

/**
 * Files a sidecar for any WAV that has none, so a recording whose app never
 * got to stop it is still browsable.
 *
 * The gap this closes: `listRecordings` enumerates sidecars, and the sidecar is
 * only written once a take stops (`recordingPipeline.ts`). Anything that ends a
 * take without going through `stopRecording` -- the webview reloading
 * mid-recording (WebView2 recreates its renderer after some resumes from
 * suspend, and the reload takes every bit of the frontend's in-memory state
 * with it), a crash, a power cut -- therefore leaves a perfectly good WAV that
 * the app can neither list, play, nor be asked to transcribe. The audio was
 * never at risk (`wav::Writer` keeps the header current after every append);
 * only the record of its existence was.
 *
 * Recovered entries are filed exactly like a record-only take: `transcribed:
 * false`, no segments, so the sidebar shows them with the "unanalyzed" badge
 * and the user can run the normal analysis on them whenever they like. The
 * live transcript that was on screen at the time is genuinely gone -- it only
 * ever lived in the store -- but re-analyzing the WAV reproduces it, and better
 * (a full-file pass beats the 15s streaming windows).
 *
 * Must only run when no take is in progress: a live recording's WAV also has
 * no sidecar yet, and filing it as an interrupted take would leave two writers'
 * worth of bookkeeping pointing at the same file. `appStore.ts` calls this once
 * at startup for exactly that reason.
 */
export async function recoverInterruptedRecordings(language: string): Promise<string[]> {
  // Nothing to recover: the mock store lives in memory and dies with the page,
  // so an "interrupted" take leaves no file behind to find.
  if (useMockBackend) return [];

  const dir = await recordingsDir();
  if (!(await exists(dir))) return [];

  const entries = await readDir(dir);
  const filed = new Set(
    entries
      .filter((e) => !e.isDirectory && e.name.endsWith(".json"))
      .map((e) => e.name.slice(0, -".json".length)),
  );

  const recovered: string[] = [];
  for (const entry of entries) {
    if (entry.isDirectory || !entry.name.endsWith(".wav")) continue;
    const id = entry.name.slice(0, -".wav".length);
    if (filed.has(id) || !parseCreatedAt(id)) continue;
    try {
      // Reads the WAV's header, not its samples -- these files run to
      // hundreds of megabytes (see `recording_duration_sec` in capture.rs).
      const durationSec = await invoke<number>("recording_duration_sec", {
        name: id,
        directory: getRecordingDirectory() || null,
      });
      if (durationSec < MIN_RECOVERABLE_SEC) continue;
      await saveRecordingHistory(id, {
        durationSec,
        language,
        transcribed: false,
        usedDiarize: false,
        usedVad: false,
        usedAudioEvents: false,
        segments: [],
        audioEvents: [],
      });
      recovered.push(id);
    } catch (err) {
      // One unreadable leftover must not stop the others from coming back --
      // same reasoning as `listRecordings` skipping a corrupt sidecar.
      console.warn(`[history] could not recover interrupted recording ${id}:`, err);
    }
  }
  return recovered;
}

/** Loads the full transcript and audio events for one history entry. */
export async function loadRecording(id: string): Promise<RecordingHistoryEntry> {
  const createdAt = parseCreatedAt(id);
  if (!createdAt) throw new Error(`${id}: not a recognized recording id`);

  if (useMockBackend) {
    const stored = mockStore.get(id);
    if (!stored) throw new Error(`${id}: not found in the mock history store`);
    return { ...metaFromStored(id, createdAt, stored), segments: stored.segments, audioEvents: stored.audioEvents };
  }

  const raw = await readTextFile(await jsonPath(id));
  const stored = JSON.parse(raw) as StoredRecording;
  return { ...metaFromStored(id, createdAt, stored), segments: stored.segments, audioEvents: stored.audioEvents };
}

/** Deletes both the sidecar JSON and the WAV. Each file is checked for
 * existence before removal and skipped if already gone -- the two can
 * legitimately go out of sync (e.g. a recording whose second pass never
 * finished has no JSON at all), and "the thing is gone either way" is the
 * only outcome the caller needs. Checking first (rather than swallowing a
 * "not found" error from `remove`) avoids depending on the exact wording of
 * an OS error message, which differs by platform. */
export async function deleteRecording(id: string): Promise<void> {
  if (useMockBackend) {
    mockStore.delete(id);
    return;
  }
  const [json, wav] = await Promise.all([jsonPath(id), wavPath(id)]);
  await Promise.all(
    [json, wav].map(async (path) => {
      if (await exists(path)) await remove(path);
    }),
  );
}
