import { readDir, readTextFile, writeTextFile, remove, exists } from "@tauri-apps/plugin-fs";
import { appCacheDir, join } from "@tauri-apps/api/path";
import type { TranscriptSegment } from "./transcript";
import type { AudioEvent } from "./asr";

/**
 * Persists finished recordings so the history sidebar can browse them across
 * app restarts. `src-tauri/src/capture.rs` already writes the audio WAV to
 * `<app cache dir>/recordings/<id>.wav` (`id` is a local-time timestamp stem
 * like `rec-20260813-084500`, generated by `capture.ts`'s `defaultName`).
 * Nothing else survives a restart today -- `segments`/`audioEvents` only ever
 * live in the Zustand store. This module adds a sidecar `<id>.json` next to
 * the WAV with everything the sidebar and the reopened transcript need, so
 * no new Rust command is required: `@tauri-apps/plugin-fs` (already a
 * dependency) reads/writes it directly from the frontend.
 */

export interface RecordingHistoryMeta {
  /** The filename stem shared with the WAV, e.g. "rec-20260813-084500". */
  id: string;
  /** Parsed back out of `id` rather than stored separately, since the
   * filename is already the source of truth for when the recording started
   * (see `capture.ts`'s `defaultName`) -- one fewer thing that could drift. */
  createdAt: Date;
  durationSec: number;
  language: string;
  /**
   * Whether this recording has been through the transcription pass at all.
   * `false` for takes made in record-only mode (see `finishRecordOnly` in
   * `appStore.ts`), whose sidecar exists only so the WAV is browsable and
   * re-analyzable -- its `segments` are empty and its `preview` is blank.
   * Everything else about the entry is real, so the sidebar renders it as a
   * normal row with an "unanalyzed" badge rather than hiding it.
   */
  transcribed: boolean;
  usedDiarize: boolean;
  usedVad: boolean;
  usedAudioEvents: boolean;
  /** First ~80 characters of the transcript, for the sidebar row. */
  preview: string;
}

export interface RecordingHistoryEntry extends RecordingHistoryMeta {
  segments: TranscriptSegment[];
  audioEvents: AudioEvent[];
}

/** On-disk JSON shape. Kept separate from `RecordingHistoryEntry` because
 * `createdAt` round-trips through JSON as a string, and derived fields
 * (`preview`) are computed on read rather than trusted from disk. */
interface StoredRecording {
  durationSec: number;
  language: string;
  /**
   * Optional on disk, required in memory: every sidecar written before
   * record-only mode existed came from the transcription pass, so a missing
   * field means `true`. Reading it as `stored.transcribed ?? true` is what
   * keeps those older recordings from all showing up as "unanalyzed".
   */
  transcribed?: boolean;
  usedDiarize: boolean;
  usedVad: boolean;
  usedAudioEvents: boolean;
  segments: TranscriptSegment[];
  audioEvents: AudioEvent[];
}

async function recordingsDir(): Promise<string> {
  return join(await appCacheDir(), "recordings");
}

async function jsonPath(id: string): Promise<string> {
  return join(await recordingsDir(), `${id}.json`);
}

/** Exported for `appStore.ts`'s `rerunHistoryEntry`, which needs the WAV
 * path to re-run the accuracy pass without a new Rust command -- the same
 * commands `refineRecording` already calls (`transcribeRecording` etc.) just
 * take a path string, so the frontend can point them at any past
 * recording's WAV, not only the one just finished. */
export async function wavPath(id: string): Promise<string> {
  return join(await recordingsDir(), `${id}.wav`);
}

/** Inverse of `capture.ts`'s `defaultName`. Returns `null` for a filename
 * that doesn't match the expected stem shape, so a stray or future file
 * format in the recordings directory is skipped rather than crashing the
 * whole list. */
function parseCreatedAt(id: string): Date | null {
  const m = /^rec-(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})(\d{2})$/.exec(id);
  if (!m) return null;
  const [, y, mo, d, h, mi, s] = m;
  const date = new Date(Number(y), Number(mo) - 1, Number(d), Number(h), Number(mi), Number(s));
  return Number.isNaN(date.getTime()) ? null : date;
}

function previewFrom(segments: TranscriptSegment[]): string {
  const text = segments
    .map((s) => s.text.trim())
    .filter(Boolean)
    .join(" ");
  return text.length > 80 ? `${text.slice(0, 80)}…` : text;
}

/**
 * Writes the sidecar JSON for a just-finished recording. `id` must be the
 * same stem `capture.start()` used for the WAV -- see `wavPath`/`jsonPath`.
 *
 * Called from `appStore.ts`'s `refineRecording` once the second pass (and
 * any diarization/audio-event passes) finish. A failure here is reported the
 * same way every other post-processing failure in that function is: a
 * `refineNotice`, not an error that discards the transcript already on
 * screen -- the recording not being *browsable later* is a smaller loss than
 * losing it *right now*.
 */
export async function saveRecordingHistory(
  id: string,
  entry: Omit<RecordingHistoryEntry, "id" | "createdAt" | "preview">,
): Promise<void> {
  const stored: StoredRecording = {
    durationSec: entry.durationSec,
    language: entry.language,
    transcribed: entry.transcribed,
    usedDiarize: entry.usedDiarize,
    usedVad: entry.usedVad,
    usedAudioEvents: entry.usedAudioEvents,
    segments: entry.segments,
    audioEvents: entry.audioEvents,
  };
  await writeTextFile(await jsonPath(id), JSON.stringify(stored));
}

/**
 * Lists past recordings, newest first. Reads and parses every sidecar JSON
 * (there is no separate lightweight index -- see the design plan for why
 * that's an acceptable tradeoff at the scale a single user's recordings
 * reach) but only keeps the small projected fields in the returned array, so
 * memory stays proportional to the recording count, not the transcript
 * length.
 *
 * A single corrupt or unreadable entry is skipped rather than failing the
 * whole list -- one bad file must not hide every other recording.
 */
export async function listRecordings(): Promise<RecordingHistoryMeta[]> {
  const dir = await recordingsDir();
  if (!(await exists(dir))) return [];

  const entries = await readDir(dir);
  const metas: RecordingHistoryMeta[] = [];
  for (const entry of entries) {
    if (entry.isDirectory || !entry.name.endsWith(".json")) continue;
    const id = entry.name.slice(0, -".json".length);
    const createdAt = parseCreatedAt(id);
    if (!createdAt) continue;
    try {
      const raw = await readTextFile(await join(dir, entry.name));
      const stored = JSON.parse(raw) as StoredRecording;
      metas.push({
        id,
        createdAt,
        durationSec: stored.durationSec,
        language: stored.language,
        transcribed: stored.transcribed ?? true,
        usedDiarize: stored.usedDiarize,
        usedVad: stored.usedVad,
        usedAudioEvents: stored.usedAudioEvents,
        preview: previewFrom(stored.segments),
      });
    } catch (err) {
      console.warn(`[history] skipping unreadable recording ${id}:`, err);
    }
  }

  return metas.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}

/** Loads the full transcript and audio events for one history entry. */
export async function loadRecording(id: string): Promise<RecordingHistoryEntry> {
  const createdAt = parseCreatedAt(id);
  if (!createdAt) throw new Error(`${id}: not a recognized recording id`);
  const raw = await readTextFile(await jsonPath(id));
  const stored = JSON.parse(raw) as StoredRecording;
  return {
    id,
    createdAt,
    durationSec: stored.durationSec,
    language: stored.language,
    transcribed: stored.transcribed ?? true,
    usedDiarize: stored.usedDiarize,
    usedVad: stored.usedVad,
    usedAudioEvents: stored.usedAudioEvents,
    preview: previewFrom(stored.segments),
    segments: stored.segments,
    audioEvents: stored.audioEvents,
  };
}

/** Deletes both the sidecar JSON and the WAV. Each file is checked for
 * existence before removal and skipped if already gone -- the two can
 * legitimately go out of sync (e.g. a recording whose second pass never
 * finished has no JSON at all), and "the thing is gone either way" is the
 * only outcome the caller needs. Checking first (rather than swallowing a
 * "not found" error from `remove`) avoids depending on the exact wording of
 * an OS error message, which differs by platform. */
export async function deleteRecording(id: string): Promise<void> {
  const [json, wav] = await Promise.all([jsonPath(id), wavPath(id)]);
  await Promise.all(
    [json, wav].map(async (path) => {
      if (await exists(path)) await remove(path);
    }),
  );
}
